use anyhow::{Context, Result};
use colored::Colorize;
use std::fs;
use std::path::PathBuf;

pub fn run(path: PathBuf, template: Option<String>) -> Result<()> {
    let target = path;
    fs::create_dir_all(&target)?;
    let agent_path = target.join("AGENT.agent");

    if agent_path.exists() && std::env::var("AGENTML_FORCE_INIT").is_err() {
        println!(
            "{}",
            "AGENT.agent already exists in this directory".yellow()
        );
        println!("Use --force or set AGENTML_FORCE_INIT=1 to overwrite.");
        return Ok(());
    }

    let (template_content, template_name) = match template.as_deref() {
        Some("rust-cli") => (rust_cli_template(), "rust-cli"),
        Some("nextjs-app") => (nextjs_app_template(), "nextjs-app"),
        Some("python-package") => (python_package_template(), "python-package"),
        _ => (generic_template(), "generic"),
    };

    fs::write(&agent_path, template_content).with_context(|| "Failed to write AGENT.agent")?;
    println!(
        "{} {}",
        "Created".green().bold(),
        agent_path.display().to_string().cyan()
    );

    // Create skills directory
    let skills_dir = target.join("skills");
    fs::create_dir_all(&skills_dir)?;
    fs::write(skills_dir.join(".gitkeep"), "")?;

    // Create .agentml directory and context
    let agentml_dir = target.join(".agentml");
    fs::create_dir_all(&agentml_dir)?;
    fs::write(
        agentml_dir.join("context.md"),
        format!(
            r#"# AgentML Context

Project: {}
Template: {}
Generated by: agentml init

## Permissions

See AGENT.agent for full permissions.

## Validation Commands

See AGENT.agent for validation commands.

## Safety Policy

See AGENT.agent for safety rules.
"#,
            template_name, template_name
        ),
    )?;

    // Create docs directory
    let docs_dir = target.join("docs");
    fs::create_dir_all(&docs_dir)?;
    fs::write(
        docs_dir.join("agentml.md"),
        format!(
            r#"# AgentML in {}

This project uses AgentML to govern AI agent behavior.

- Contract: [AGENT.agent](../AGENT.agent)
- Context: [.agentml/context.md](../.agentml/context.md)

Run validation:

```bash
agentml validate AGENT.agent
agentml self-check
```
"#,
            template_name
        ),
    )?;

    // Create .github/workflows
    let workflow_dir = target.join(".github").join("workflows");
    fs::create_dir_all(&workflow_dir)?;
    fs::write(workflow_dir.join("agentml-check.yml"), workflow_template())?;

    println!("{}", "Template structure created.".dimmed());
    println!();
    println!("Next steps:");
    println!("  1. Edit AGENT.agent for your project");
    println!("  2. Run: agentml validate AGENT.agent");
    println!("  3. Run: agentml self-check");
    Ok(())
}

fn generic_template() -> &'static str {
    r#"# AgentML Execution Contract
meta:
  name: my-project
  version: "1.0.0"
  description: "Short description of what this agent should do"

purpose: >
  Describe the agent's purpose and what it is allowed to do.
  Be specific about goals and constraints.

context:
  project_type: generic
  languages: []
  frameworks: []

permissions:
  read:
    - "**/*"
  write:
    - "src/**/*"
    - "docs/**/*"
  execute:
    - "npm run"
    - "cargo"
    - "python"

tools: [git, bash, npm]

safety:
  policy: "Never commit secrets. Use environment variables."
  forbidden_paths:
    - ".env*"
    - "node_modules/**"
  forbidden_actions:
    - "rm -rf src"
    - "git push --force"
  require_confirmation:
    - "git push"

validation:
  - name: Lint
    command: "npm run lint"

output:
  format: markdown
  required_sections:
    - "summary"
    - "changes"
"#
}

fn rust_cli_template() -> &'static str {
    r#"# AgentML Execution Contract
meta:
  name: my-rust-cli
  version: "1.0.0"

purpose: >
  AI agent for developing and maintaining a Rust CLI application.

context:
  project_type: rust-cli
  languages: [rust]
  frameworks: [clap, tokio]

permissions:
  read:
    - "**/*.rs"
    - "**/Cargo.toml"
    - "**/*.md"
  write:
    - "src/**/*.rs"
    - "Cargo.toml"
  execute:
    - "cargo"
    - "rustfmt"
    - "clippy"

tools: [cargo, rustfmt, clippy, git, bash]

safety:
  policy: >
    Never delete code without creating a commit first.
    Require human review for all releases and dependency updates.
  forbidden_paths:
    - "target/**"
    - "**/*.rs.bk"
  forbidden_actions:
    - "cargo publish"
    - "rm -rf src"
  require_confirmation:
    - "cargo publish"
    - "cargo install"

validation:
  - name: Format
    command: "cargo fmt -- --check"
  - name: Clippy
    command: "cargo clippy -- -D warnings"
  - name: Test
    command: "cargo test"

output:
  format: markdown
  required_sections:
    - "changes"
    - "tests"
    - "risks"
"#
}

fn nextjs_app_template() -> &'static str {
    r#"# AgentML Execution Contract
meta:
  name: my-nextjs-app
  version: "1.0.0"

purpose: >
  AI agent for building and maintaining a Next.js application.

context:
  project_type: nextjs
  languages: [typescript, javascript]
  frameworks: [nextjs, react]

permissions:
  read:
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.json"
    - "**/*.md"
  write:
    - "src/**/*.ts"
    - "src/**/*.tsx"
    - "app/**/*.tsx"
  execute:
    - "npm run"
    - "npx"

tools: [npm, node, git, bash]

safety:
  policy: >
    Never commit secrets. Use environment variables and .env.local.
    Require human review for all git push and database changes.
  forbidden_paths:
    - ".env*.local"
    - ".env.production"
    - "node_modules/**"
  forbidden_actions:
    - "git push --force"
    - "rm -rf src"
  require_confirmation:
    - "git push"
    - "npm run db:migrate"

validation:
  - name: Lint
    command: "npm run lint"
  - name: Type Check
    command: "npm run typecheck"
  - name: Test
    command: "npm test"

output:
  format: markdown
  required_sections:
    - "changes"
    - "tests"
    - "risks"
"#
}

fn python_package_template() -> &'static str {
    r#"# AgentML Execution Contract
meta:
  name: my-python-package
  version: "1.0.0"

purpose: >
  AI agent for developing and maintaining a Python package.

context:
  project_type: python-package
  languages: [python]
  frameworks: [pytest, ruff]

permissions:
  read:
    - "**/*.py"
    - "**/pyproject.toml"
    - "**/*.md"
  write:
    - "src/**/*.py"
    - "tests/**/*.py"
    - "pyproject.toml"
  execute:
    - "python"
    - "pytest"
    - "ruff"

tools: [python, pip, git, bash]

safety:
  policy: "Never commit secrets. Use environment variables."
  forbidden_paths:
    - ".venv/**"
    - "dist/**"
    - "*.egg-info"
  forbidden_actions:
    - "rm -rf src"
    - "git push --force"
  require_confirmation:
    - "git push"
    - "twine upload"

validation:
  - name: Lint
    command: "ruff check ."
  - name: Test
    command: "pytest"

output:
  format: markdown
  required_sections:
    - "changes"
    - "tests"
    - "risks"
"#
}

fn workflow_template() -> &'static str {
    r#"name: AgentML Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  agentml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test
      - run: cargo run -- validate AGENT.agent
      - run: cargo run -- skill validate skills/*.skill
      - run: cargo run -- self-check
"#
}
